#!/bin/sh

export U_ENV="none"

if [ "$#" -eq 0 ]; then
    exit 255
fi

while [ "$#" -gt 0 ]; do
    case "$1" in
    d | dev)
        U_ENV="DEVELOPMENT"
        ;;
    s | stg)
        U_ENV="STAGING"
        ;;
    p | prod)
        U_ENV="PRODUCTION"
        ;;
    *)
        exit 255
        ;;
    esac
    shift
done

echo "NODE_ENV=$NODE_ENV" >>.env.local \
&& echo "NEXT_PUBLIC_ENVIRONMENT=$U_ENV" >>.env.local \
&& echo "NEXT_PUBLIC_API_URL=$API_URL" >>.env.local \
&& echo "NEXT_PUBLIC_G_OPTIMIZE_KEY=$G_OPTIMIZE_KEY" >>.env.local \
&& echo "NEXT_PUBLIC_GA_KEY=$GA_KEY" >>.env.local \
&& echo "NEXT_PUBLIC_HOTJAR_SITE_ID=$HOTJAR_SITE_ID" >>.env.local \
&& echo "NEXT_PUBLIC_SENTRY_ENVIRONMENT=$U_ENV" >>.env.local \
&& echo "NEXT_PUBLIC_SENTRY_DSN=$SENTRY_DSN" >>.env.local \
&& echo "NEXT_PUBLIC_NPM_PACKAGE_VERSION=$(jq -r .version package.json)" >>.env.local

echo "token=$SENTRYCLIRC_TOKEN" >>.sentryclirc
